services:
  frontend:

    container_name: bolsatrabajo-frontend
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      - NODE_ENV=production