services:
  frontend:
    container_name: bolsadetrabajo-frontend
    restart: unless-stopped
    image: bolsadetrabajo-frontend:v1.0.0
    build:
      context: .
      dockerfile: Dockerfile
      target: production
      args:
        - VITE_PORT=${VITE_PORT}
        - NODE_ENV=production

    ports:
      - "${VITE_PORT}:${VITE_PORT}"
    env_file:
      - .env
    environment:
      - NODE_ENV=production
    networks:
      - api_network
networks:
    api_network:
        external: true