services:
  frontend:
    image: bolsatrabajo
    container_name: bolsatrabajo
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=production